# Generated by Django 3.1.2 on 2020-10-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201025_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='example@domain.com', max_length=50),
        ),
    ]
